### ISSUE TITLE
Upgrade of Helm deployment of this chart fails

### ISSUE THREAD

**Issue by nickperry** [PaloAltoNetworks/cortex-helm#18]
## Describe the bug

When no pull secret is set in the chart values, upgrade of deployments of this chart will fail.

## Expected behavior

Upgrade should work if no pull secret is set.

## Current behavior

```
  Error: UPGRADE FAILED: failed to create patch: map: map[] does not contain declared merge key: name
```

## Possible solution

Wrap part of the template in a conditional, based on whether .Values.dockerPullSecretName is set

## Steps to reproduce

Deploy the chart, with .Values.dockerPullSecretName unset.
Upgrade the deployment

## Screenshots

```
  Error: UPGRADE FAILED: failed to create patch: map: map[] does not contain declared merge key: name
```

## Context

Means we cannot use the cortex chart.

## Your Environment

cortex-agent-8.1.1.112729
Kubernetes 1.26
Linux

**Comment by ranberant** [comment]
Fixed in version 1.6.0
